### ISSUE TITLE
import LitElement fails from JSPM for Google Mobile Friendly test

### ISSUE THREAD

**Issue by DanielKehoe** [InstallGuides/install-guide#1]
I'm comparing use of LitElement imported from two module CDNs, jspm.dev and skypack.dev. Skypack succeeds and JSPM fails.

Here are two test pages:

- [https://install.guide/test-skypack.html](https://install.guide/test-skypack.html)
- [https://install.guide/test-jspm.html](https://install.guide/test-jspm.html)

You can test with the Google Mobile Friendly test site:
[https://search.google.com/test/mobile-friendly](https://search.google.com/test/mobile-friendly)

With the JSPM page, the screenshot will be blank. Click "Page loading issues: VIEW DETAILS".

The error is

```
Page partially loaded. Not all page resources could be loaded.
6 page resources couldn’t be loaded
```
With the Skypack page, the screenshot appears and there are no loading issues.

Additional notes: I first encountered the issue using the Google Search Console to check if pages using web components were being indexed by the GoogleBot. The issue is the same. It's easier to test with the Google Mobile Friendly test site (presumably using the same test facility as the Google Search Console).

You can find the code for the two test pages and two web components in this repository:

https://github.com/InstallGuides/install-guide/blob/main/test-jspm.html
https://github.com/InstallGuides/install-guide/blob/main/assets/scripts/yax-tag-jspm.js

![jspm-fails](https://user-images.githubusercontent.com/950301/103636942-ad335800-4f85-11eb-95c8-4293d7c6c44f.png)

![skypack-succeeds](https://user-images.githubusercontent.com/950301/103637067-deac2380-4f85-11eb-950a-fde5c6d87a9f.png)

**Comment by guybedford** [comment]
This issue should be resolved now - turned out this was due to an invalid robots.txt file.

**Comment by DanielKehoe** [comment]
@guybedford could you doublecheck and give me the screenshot from the Mobile_Friendly Test? Because I am still getting the same "Page partially loaded" result.

**Comment by guybedford** [comment]
So here's something quite odd, while I can see that your test is failing when I run it, I also hosted another version on the jspm servers here - https://jspm.dev/-keyboardevent/test.html, which when you paste that in is definitely showing it passing ok (the screenshot shows up and there are no script errors).

I think the issue is that the bot doesn't support brotli compression properly - or at least there is a bug in its interpretation code. jspm serves brotli by default instead of gzip because of the compression benefits and because all browsers with ES module support support brotli.

The System CDN does support gzip though as it is designed for older browsers. So for example https://jspm.org/test.html is a SystemJS version of the same page which works here.

Supporting for both brotli and gzip on the CDN will be provided in the next release, but that is three months away still.

**Comment by DanielKehoe** [comment]
Closing this issue. Unresolved. Testing pages with Google Mobile Friendly or Google Search Console continues to give errors indicating page resources can't be loaded from jspm.dev. Will work around the problem by bundling all libraries or loading from Skypack. Plan to revisit the issue and test again after the next release of the jspm.dev CDN.
